spring:
  application:
    name: transaction-service

  config:
    import: optional:configserver:http://localhost:8080

  kafka:
    bootstrap-servers: localhost:9092

    consumer:
      group-id: account-group
      auto-offset-reset: earliest

    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
