spring:
  application:
    name: account-service

  config:
    import: optional:configserver:http://localhost:8080

  kafka:
    consumer:
      bootstrap-servers: localhost:9092
      group-id: account-group
      auto-offset-reset: earliest

    listener:
      ack-mode: record

logging:
  level:
    root: INFO
  pattern:
    console: >
      {"timestamp":"%d{yyyy-MM-dd HH:mm:ss}",
        "level":"%p",
        "service":"account-service",
        "correlationId":"%X{correlationId}",
        "message":"%m"}

  management:
    tracing:
      sampling:
        probability: 1.0

    endpoints:
      web:
        exposure:
          include: health,info,prometheus
      endpoint:
        prometheus:
          enabled: true


  otel:
    exporter:
      otlp:
        endpoint: http://localhost:4318