server:
  port: 8080

spring:
  application:
    name: config-server

  profiles:
    active: git

  cloud:
    config:
      server:
        git:
          uri: https://github.com/GermanCarrasco/config-repository
          default-label: main
          clone-on-start: true

management:
  endpoints:
    web:
      exposure:
        include: "*"